/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DireitosRouteImport } from './routes/direitos'
import { Route as IndexRouteImport } from './routes/index'

const DireitosRoute = DireitosRouteImport.update({
  id: '/direitos',
  path: '/direitos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/direitos': typeof DireitosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/direitos': typeof DireitosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/direitos': typeof DireitosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/direitos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/direitos'
  id: '__root__' | '/' | '/direitos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DireitosRoute: typeof DireitosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/direitos': {
      id: '/direitos'
      path: '/direitos'
      fullPath: '/direitos'
      preLoaderRoute: typeof DireitosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DireitosRoute: DireitosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
